/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Beach brand e-commerce API
 * OpenAPI spec version: 0.1.0
 */
export interface SiteSettings {
    heroTitle: string;
    heroSubtitle: string;
    heroVideoUrl: string;
    heroButton1?: string;
    heroButton2?: string;
    newsletterText: string;
    footerText: string;
}
//# sourceMappingURL=siteSettings.d.ts.map