/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Beach brand e-commerce API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List products with optional filters
 */
export declare const ListProductsQueryParams: zod.ZodObject<{
    category: zod.ZodOptional<zod.ZodString>;
    size: zod.ZodOptional<zod.ZodString>;
    color: zod.ZodOptional<zod.ZodString>;
    minPrice: zod.ZodOptional<zod.ZodNumber>;
    maxPrice: zod.ZodOptional<zod.ZodNumber>;
    search: zod.ZodOptional<zod.ZodString>;
    featured: zod.ZodOptional<zod.ZodBoolean>;
    bestSeller: zod.ZodOptional<zod.ZodBoolean>;
    page: zod.ZodOptional<zod.ZodNumber>;
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    category?: string | undefined;
    size?: string | undefined;
    color?: string | undefined;
    minPrice?: number | undefined;
    maxPrice?: number | undefined;
    search?: string | undefined;
    featured?: boolean | undefined;
    bestSeller?: boolean | undefined;
    page?: number | undefined;
    limit?: number | undefined;
}, {
    category?: string | undefined;
    size?: string | undefined;
    color?: string | undefined;
    minPrice?: number | undefined;
    maxPrice?: number | undefined;
    search?: string | undefined;
    featured?: boolean | undefined;
    bestSeller?: boolean | undefined;
    page?: number | undefined;
    limit?: number | undefined;
}>;
export declare const ListProductsResponse: zod.ZodObject<{
    products: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        price: zod.ZodNumber;
        images: zod.ZodArray<zod.ZodString, "many">;
        sizes: zod.ZodArray<zod.ZodString, "many">;
        colors: zod.ZodArray<zod.ZodString, "many">;
        category: zod.ZodString;
        stock: zod.ZodNumber;
        isFeatured: zod.ZodBoolean;
        isBestSeller: zod.ZodBoolean;
    }, "strip", zod.ZodTypeAny, {
        category: string;
        id: number;
        name: string;
        price: number;
        images: string[];
        sizes: string[];
        colors: string[];
        stock: number;
        isFeatured: boolean;
        isBestSeller: boolean;
        description?: string | null | undefined;
    }, {
        category: string;
        id: number;
        name: string;
        price: number;
        images: string[];
        sizes: string[];
        colors: string[];
        stock: number;
        isFeatured: boolean;
        isBestSeller: boolean;
        description?: string | null | undefined;
    }>, "many">;
    total: zod.ZodNumber;
    page: zod.ZodNumber;
    totalPages: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    page: number;
    products: {
        category: string;
        id: number;
        name: string;
        price: number;
        images: string[];
        sizes: string[];
        colors: string[];
        stock: number;
        isFeatured: boolean;
        isBestSeller: boolean;
        description?: string | null | undefined;
    }[];
    total: number;
    totalPages: number;
}, {
    page: number;
    products: {
        category: string;
        id: number;
        name: string;
        price: number;
        images: string[];
        sizes: string[];
        colors: string[];
        stock: number;
        isFeatured: boolean;
        isBestSeller: boolean;
        description?: string | null | undefined;
    }[];
    total: number;
    totalPages: number;
}>;
/**
 * @summary Create a new product (admin)
 */
export declare const CreateProductBody: zod.ZodObject<{
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    price: zod.ZodNumber;
    images: zod.ZodOptional<zod.ZodArray<zod.ZodString, "many">>;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodOptional<zod.ZodBoolean>;
    isBestSeller: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    category: string;
    name: string;
    price: number;
    sizes: string[];
    colors: string[];
    stock: number;
    description?: string | undefined;
    images?: string[] | undefined;
    isFeatured?: boolean | undefined;
    isBestSeller?: boolean | undefined;
}, {
    category: string;
    name: string;
    price: number;
    sizes: string[];
    colors: string[];
    stock: number;
    description?: string | undefined;
    images?: string[] | undefined;
    isFeatured?: boolean | undefined;
    isBestSeller?: boolean | undefined;
}>;
export declare const CreateProductResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>;
/**
 * @summary Get product by ID
 */
export declare const GetProductParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetProductResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>;
/**
 * @summary Update a product (admin)
 */
export declare const UpdateProductParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateProductBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodString>;
    price: zod.ZodOptional<zod.ZodNumber>;
    images: zod.ZodOptional<zod.ZodArray<zod.ZodString, "many">>;
    sizes: zod.ZodOptional<zod.ZodArray<zod.ZodString, "many">>;
    colors: zod.ZodOptional<zod.ZodArray<zod.ZodString, "many">>;
    category: zod.ZodOptional<zod.ZodString>;
    stock: zod.ZodOptional<zod.ZodNumber>;
    isFeatured: zod.ZodOptional<zod.ZodBoolean>;
    isBestSeller: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    category?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    images?: string[] | undefined;
    sizes?: string[] | undefined;
    colors?: string[] | undefined;
    stock?: number | undefined;
    isFeatured?: boolean | undefined;
    isBestSeller?: boolean | undefined;
}, {
    category?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    images?: string[] | undefined;
    sizes?: string[] | undefined;
    colors?: string[] | undefined;
    stock?: number | undefined;
    isFeatured?: boolean | undefined;
    isBestSeller?: boolean | undefined;
}>;
export declare const UpdateProductResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>;
/**
 * @summary Delete a product (admin)
 */
export declare const DeleteProductParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeleteProductResponse: zod.ZodVoid;
/**
 * @summary Get featured products for homepage
 */
export declare const GetFeaturedProductsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>;
export declare const GetFeaturedProductsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>, "many">;
/**
 * @summary Get best-selling products
 */
export declare const GetBestSellersResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>;
export declare const GetBestSellersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>, "many">;
/**
 * @summary Get related products
 */
export declare const GetRelatedProductsParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetRelatedProductsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>;
export declare const GetRelatedProductsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>, "many">;
/**
 * @summary Get cart by session
 */
export declare const GetCartQueryParams: zod.ZodObject<{
    sessionId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
}, {
    sessionId: string;
}>;
export declare const GetCartResponse: zod.ZodObject<{
    sessionId: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        productId: zod.ZodNumber;
        quantity: zod.ZodNumber;
        size: zod.ZodString;
        color: zod.ZodString;
        product: zod.ZodObject<{
            id: zod.ZodNumber;
            name: zod.ZodString;
            description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            price: zod.ZodNumber;
            images: zod.ZodArray<zod.ZodString, "many">;
            sizes: zod.ZodArray<zod.ZodString, "many">;
            colors: zod.ZodArray<zod.ZodString, "many">;
            category: zod.ZodString;
            stock: zod.ZodNumber;
            isFeatured: zod.ZodBoolean;
            isBestSeller: zod.ZodBoolean;
        }, "strip", zod.ZodTypeAny, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }>, "many">;
    subtotal: zod.ZodNumber;
    total: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    total: number;
    sessionId: string;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
}, {
    total: number;
    sessionId: string;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
}>;
/**
 * @summary Add item to cart
 */
export declare const AddToCartBody: zod.ZodObject<{
    sessionId: zod.ZodString;
    productId: zod.ZodNumber;
    quantity: zod.ZodNumber;
    size: zod.ZodString;
    color: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    size: string;
    color: string;
    sessionId: string;
    productId: number;
    quantity: number;
}, {
    size: string;
    color: string;
    sessionId: string;
    productId: number;
    quantity: number;
}>;
export declare const AddToCartResponse: zod.ZodObject<{
    sessionId: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        productId: zod.ZodNumber;
        quantity: zod.ZodNumber;
        size: zod.ZodString;
        color: zod.ZodString;
        product: zod.ZodObject<{
            id: zod.ZodNumber;
            name: zod.ZodString;
            description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            price: zod.ZodNumber;
            images: zod.ZodArray<zod.ZodString, "many">;
            sizes: zod.ZodArray<zod.ZodString, "many">;
            colors: zod.ZodArray<zod.ZodString, "many">;
            category: zod.ZodString;
            stock: zod.ZodNumber;
            isFeatured: zod.ZodBoolean;
            isBestSeller: zod.ZodBoolean;
        }, "strip", zod.ZodTypeAny, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }>, "many">;
    subtotal: zod.ZodNumber;
    total: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    total: number;
    sessionId: string;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
}, {
    total: number;
    sessionId: string;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
}>;
/**
 * @summary Update cart item quantity
 */
export declare const UpdateCartItemParams: zod.ZodObject<{
    sessionId: zod.ZodString;
    productId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
    productId: number;
}, {
    sessionId: string;
    productId: number;
}>;
export declare const UpdateCartItemBody: zod.ZodObject<{
    quantity: zod.ZodNumber;
    size: zod.ZodOptional<zod.ZodString>;
    color: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    quantity: number;
    size?: string | undefined;
    color?: string | undefined;
}, {
    quantity: number;
    size?: string | undefined;
    color?: string | undefined;
}>;
export declare const UpdateCartItemResponse: zod.ZodObject<{
    sessionId: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        productId: zod.ZodNumber;
        quantity: zod.ZodNumber;
        size: zod.ZodString;
        color: zod.ZodString;
        product: zod.ZodObject<{
            id: zod.ZodNumber;
            name: zod.ZodString;
            description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            price: zod.ZodNumber;
            images: zod.ZodArray<zod.ZodString, "many">;
            sizes: zod.ZodArray<zod.ZodString, "many">;
            colors: zod.ZodArray<zod.ZodString, "many">;
            category: zod.ZodString;
            stock: zod.ZodNumber;
            isFeatured: zod.ZodBoolean;
            isBestSeller: zod.ZodBoolean;
        }, "strip", zod.ZodTypeAny, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }>, "many">;
    subtotal: zod.ZodNumber;
    total: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    total: number;
    sessionId: string;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
}, {
    total: number;
    sessionId: string;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
}>;
/**
 * @summary Remove item from cart
 */
export declare const RemoveFromCartParams: zod.ZodObject<{
    sessionId: zod.ZodString;
    productId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
    productId: number;
}, {
    sessionId: string;
    productId: number;
}>;
export declare const RemoveFromCartResponse: zod.ZodObject<{
    sessionId: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        productId: zod.ZodNumber;
        quantity: zod.ZodNumber;
        size: zod.ZodString;
        color: zod.ZodString;
        product: zod.ZodObject<{
            id: zod.ZodNumber;
            name: zod.ZodString;
            description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            price: zod.ZodNumber;
            images: zod.ZodArray<zod.ZodString, "many">;
            sizes: zod.ZodArray<zod.ZodString, "many">;
            colors: zod.ZodArray<zod.ZodString, "many">;
            category: zod.ZodString;
            stock: zod.ZodNumber;
            isFeatured: zod.ZodBoolean;
            isBestSeller: zod.ZodBoolean;
        }, "strip", zod.ZodTypeAny, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }>, "many">;
    subtotal: zod.ZodNumber;
    total: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    total: number;
    sessionId: string;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
}, {
    total: number;
    sessionId: string;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
}>;
/**
 * @summary Place an order
 */
export declare const CreateOrderBody: zod.ZodObject<{
    customerName: zod.ZodString;
    customerEmail: zod.ZodString;
    customerPhone: zod.ZodString;
    address: zod.ZodString;
    city: zod.ZodString;
    paymentMethod: zod.ZodString;
    sessionId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    address: string;
    city: string;
    paymentMethod: string;
}, {
    sessionId: string;
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    address: string;
    city: string;
    paymentMethod: string;
}>;
export declare const CreateOrderResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    customerName: zod.ZodString;
    customerEmail: zod.ZodString;
    customerPhone: zod.ZodString;
    address: zod.ZodString;
    city: zod.ZodString;
    paymentMethod: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        productId: zod.ZodNumber;
        quantity: zod.ZodNumber;
        size: zod.ZodString;
        color: zod.ZodString;
        product: zod.ZodObject<{
            id: zod.ZodNumber;
            name: zod.ZodString;
            description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            price: zod.ZodNumber;
            images: zod.ZodArray<zod.ZodString, "many">;
            sizes: zod.ZodArray<zod.ZodString, "many">;
            colors: zod.ZodArray<zod.ZodString, "many">;
            category: zod.ZodString;
            stock: zod.ZodNumber;
            isFeatured: zod.ZodBoolean;
            isBestSeller: zod.ZodBoolean;
        }, "strip", zod.ZodTypeAny, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }>, "many">;
    subtotal: zod.ZodNumber;
    total: zod.ZodNumber;
    status: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    total: number;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    address: string;
    city: string;
    paymentMethod: string;
    createdAt: string;
}, {
    status: string;
    id: number;
    total: number;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    address: string;
    city: string;
    paymentMethod: string;
    createdAt: string;
}>;
/**
 * @summary List all orders (admin)
 */
export declare const ListOrdersResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    customerName: zod.ZodString;
    customerEmail: zod.ZodString;
    customerPhone: zod.ZodString;
    address: zod.ZodString;
    city: zod.ZodString;
    paymentMethod: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        productId: zod.ZodNumber;
        quantity: zod.ZodNumber;
        size: zod.ZodString;
        color: zod.ZodString;
        product: zod.ZodObject<{
            id: zod.ZodNumber;
            name: zod.ZodString;
            description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            price: zod.ZodNumber;
            images: zod.ZodArray<zod.ZodString, "many">;
            sizes: zod.ZodArray<zod.ZodString, "many">;
            colors: zod.ZodArray<zod.ZodString, "many">;
            category: zod.ZodString;
            stock: zod.ZodNumber;
            isFeatured: zod.ZodBoolean;
            isBestSeller: zod.ZodBoolean;
        }, "strip", zod.ZodTypeAny, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }>, "many">;
    subtotal: zod.ZodNumber;
    total: zod.ZodNumber;
    status: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    total: number;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    address: string;
    city: string;
    paymentMethod: string;
    createdAt: string;
}, {
    status: string;
    id: number;
    total: number;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    address: string;
    city: string;
    paymentMethod: string;
    createdAt: string;
}>;
export declare const ListOrdersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    customerName: zod.ZodString;
    customerEmail: zod.ZodString;
    customerPhone: zod.ZodString;
    address: zod.ZodString;
    city: zod.ZodString;
    paymentMethod: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        productId: zod.ZodNumber;
        quantity: zod.ZodNumber;
        size: zod.ZodString;
        color: zod.ZodString;
        product: zod.ZodObject<{
            id: zod.ZodNumber;
            name: zod.ZodString;
            description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            price: zod.ZodNumber;
            images: zod.ZodArray<zod.ZodString, "many">;
            sizes: zod.ZodArray<zod.ZodString, "many">;
            colors: zod.ZodArray<zod.ZodString, "many">;
            category: zod.ZodString;
            stock: zod.ZodNumber;
            isFeatured: zod.ZodBoolean;
            isBestSeller: zod.ZodBoolean;
        }, "strip", zod.ZodTypeAny, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }, {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }, {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }>, "many">;
    subtotal: zod.ZodNumber;
    total: zod.ZodNumber;
    status: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    total: number;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    address: string;
    city: string;
    paymentMethod: string;
    createdAt: string;
}, {
    status: string;
    id: number;
    total: number;
    items: {
        size: string;
        color: string;
        id: number;
        productId: number;
        quantity: number;
        product: {
            category: string;
            id: number;
            name: string;
            price: number;
            images: string[];
            sizes: string[];
            colors: string[];
            stock: number;
            isFeatured: boolean;
            isBestSeller: boolean;
            description?: string | null | undefined;
        };
    }[];
    subtotal: number;
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    address: string;
    city: string;
    paymentMethod: string;
    createdAt: string;
}>, "many">;
/**
 * @summary Get wishlist by session
 */
export declare const GetWishlistQueryParams: zod.ZodObject<{
    sessionId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
}, {
    sessionId: string;
}>;
export declare const GetWishlistResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>;
export declare const GetWishlistResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>, "many">;
/**
 * @summary Toggle product in wishlist
 */
export declare const AddToWishlistBody: zod.ZodObject<{
    sessionId: zod.ZodString;
    productId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
    productId: number;
}, {
    sessionId: string;
    productId: number;
}>;
export declare const AddToWishlistResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>;
export declare const AddToWishlistResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    images: zod.ZodArray<zod.ZodString, "many">;
    sizes: zod.ZodArray<zod.ZodString, "many">;
    colors: zod.ZodArray<zod.ZodString, "many">;
    category: zod.ZodString;
    stock: zod.ZodNumber;
    isFeatured: zod.ZodBoolean;
    isBestSeller: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}, {
    category: string;
    id: number;
    name: string;
    price: number;
    images: string[];
    sizes: string[];
    colors: string[];
    stock: number;
    isFeatured: boolean;
    isBestSeller: boolean;
    description?: string | null | undefined;
}>, "many">;
/**
 * @summary List customer reviews
 */
export declare const ListReviewsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    rating: zod.ZodNumber;
    comment: zod.ZodString;
    location: zod.ZodString;
    avatar: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    rating: number;
    comment: string;
    location: string;
    avatar?: string | null | undefined;
}, {
    id: number;
    name: string;
    rating: number;
    comment: string;
    location: string;
    avatar?: string | null | undefined;
}>;
export declare const ListReviewsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    rating: zod.ZodNumber;
    comment: zod.ZodString;
    location: zod.ZodString;
    avatar: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    rating: number;
    comment: string;
    location: string;
    avatar?: string | null | undefined;
}, {
    id: number;
    name: string;
    rating: number;
    comment: string;
    location: string;
    avatar?: string | null | undefined;
}>, "many">;
/**
 * @summary Admin login with password
 */
export declare const AdminLoginBody: zod.ZodObject<{
    password: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    password: string;
}, {
    password: string;
}>;
export declare const AdminLoginResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
    token: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    success: boolean;
    token: string;
}, {
    success: boolean;
    token: string;
}>;
/**
 * @summary Get admin dashboard statistics
 */
export declare const GetAdminStatsResponse: zod.ZodObject<{
    totalOrders: zod.ZodNumber;
    totalRevenue: zod.ZodNumber;
    totalProducts: zod.ZodNumber;
    totalCustomers: zod.ZodNumber;
    recentOrders: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        customerName: zod.ZodString;
        customerEmail: zod.ZodString;
        customerPhone: zod.ZodString;
        address: zod.ZodString;
        city: zod.ZodString;
        paymentMethod: zod.ZodString;
        items: zod.ZodArray<zod.ZodObject<{
            id: zod.ZodNumber;
            productId: zod.ZodNumber;
            quantity: zod.ZodNumber;
            size: zod.ZodString;
            color: zod.ZodString;
            product: zod.ZodObject<{
                id: zod.ZodNumber;
                name: zod.ZodString;
                description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
                price: zod.ZodNumber;
                images: zod.ZodArray<zod.ZodString, "many">;
                sizes: zod.ZodArray<zod.ZodString, "many">;
                colors: zod.ZodArray<zod.ZodString, "many">;
                category: zod.ZodString;
                stock: zod.ZodNumber;
                isFeatured: zod.ZodBoolean;
                isBestSeller: zod.ZodBoolean;
            }, "strip", zod.ZodTypeAny, {
                category: string;
                id: number;
                name: string;
                price: number;
                images: string[];
                sizes: string[];
                colors: string[];
                stock: number;
                isFeatured: boolean;
                isBestSeller: boolean;
                description?: string | null | undefined;
            }, {
                category: string;
                id: number;
                name: string;
                price: number;
                images: string[];
                sizes: string[];
                colors: string[];
                stock: number;
                isFeatured: boolean;
                isBestSeller: boolean;
                description?: string | null | undefined;
            }>;
        }, "strip", zod.ZodTypeAny, {
            size: string;
            color: string;
            id: number;
            productId: number;
            quantity: number;
            product: {
                category: string;
                id: number;
                name: string;
                price: number;
                images: string[];
                sizes: string[];
                colors: string[];
                stock: number;
                isFeatured: boolean;
                isBestSeller: boolean;
                description?: string | null | undefined;
            };
        }, {
            size: string;
            color: string;
            id: number;
            productId: number;
            quantity: number;
            product: {
                category: string;
                id: number;
                name: string;
                price: number;
                images: string[];
                sizes: string[];
                colors: string[];
                stock: number;
                isFeatured: boolean;
                isBestSeller: boolean;
                description?: string | null | undefined;
            };
        }>, "many">;
        subtotal: zod.ZodNumber;
        total: zod.ZodNumber;
        status: zod.ZodString;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: number;
        total: number;
        items: {
            size: string;
            color: string;
            id: number;
            productId: number;
            quantity: number;
            product: {
                category: string;
                id: number;
                name: string;
                price: number;
                images: string[];
                sizes: string[];
                colors: string[];
                stock: number;
                isFeatured: boolean;
                isBestSeller: boolean;
                description?: string | null | undefined;
            };
        }[];
        subtotal: number;
        customerName: string;
        customerEmail: string;
        customerPhone: string;
        address: string;
        city: string;
        paymentMethod: string;
        createdAt: string;
    }, {
        status: string;
        id: number;
        total: number;
        items: {
            size: string;
            color: string;
            id: number;
            productId: number;
            quantity: number;
            product: {
                category: string;
                id: number;
                name: string;
                price: number;
                images: string[];
                sizes: string[];
                colors: string[];
                stock: number;
                isFeatured: boolean;
                isBestSeller: boolean;
                description?: string | null | undefined;
            };
        }[];
        subtotal: number;
        customerName: string;
        customerEmail: string;
        customerPhone: string;
        address: string;
        city: string;
        paymentMethod: string;
        createdAt: string;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    totalOrders: number;
    totalRevenue: number;
    totalProducts: number;
    totalCustomers: number;
    recentOrders: {
        status: string;
        id: number;
        total: number;
        items: {
            size: string;
            color: string;
            id: number;
            productId: number;
            quantity: number;
            product: {
                category: string;
                id: number;
                name: string;
                price: number;
                images: string[];
                sizes: string[];
                colors: string[];
                stock: number;
                isFeatured: boolean;
                isBestSeller: boolean;
                description?: string | null | undefined;
            };
        }[];
        subtotal: number;
        customerName: string;
        customerEmail: string;
        customerPhone: string;
        address: string;
        city: string;
        paymentMethod: string;
        createdAt: string;
    }[];
}, {
    totalOrders: number;
    totalRevenue: number;
    totalProducts: number;
    totalCustomers: number;
    recentOrders: {
        status: string;
        id: number;
        total: number;
        items: {
            size: string;
            color: string;
            id: number;
            productId: number;
            quantity: number;
            product: {
                category: string;
                id: number;
                name: string;
                price: number;
                images: string[];
                sizes: string[];
                colors: string[];
                stock: number;
                isFeatured: boolean;
                isBestSeller: boolean;
                description?: string | null | undefined;
            };
        }[];
        subtotal: number;
        customerName: string;
        customerEmail: string;
        customerPhone: string;
        address: string;
        city: string;
        paymentMethod: string;
        createdAt: string;
    }[];
}>;
/**
 * @summary Get site settings (hero, footer, newsletter)
 */
export declare const GetSettingsResponse: zod.ZodObject<{
    heroTitle: zod.ZodString;
    heroSubtitle: zod.ZodString;
    heroVideoUrl: zod.ZodString;
    heroButton1: zod.ZodOptional<zod.ZodString>;
    heroButton2: zod.ZodOptional<zod.ZodString>;
    newsletterText: zod.ZodString;
    footerText: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    heroTitle: string;
    heroSubtitle: string;
    heroVideoUrl: string;
    newsletterText: string;
    footerText: string;
    heroButton1?: string | undefined;
    heroButton2?: string | undefined;
}, {
    heroTitle: string;
    heroSubtitle: string;
    heroVideoUrl: string;
    newsletterText: string;
    footerText: string;
    heroButton1?: string | undefined;
    heroButton2?: string | undefined;
}>;
/**
 * @summary Update site settings (admin)
 */
export declare const UpdateSettingsBody: zod.ZodObject<{
    heroTitle: zod.ZodOptional<zod.ZodString>;
    heroSubtitle: zod.ZodOptional<zod.ZodString>;
    heroVideoUrl: zod.ZodOptional<zod.ZodString>;
    heroButton1: zod.ZodOptional<zod.ZodString>;
    heroButton2: zod.ZodOptional<zod.ZodString>;
    newsletterText: zod.ZodOptional<zod.ZodString>;
    footerText: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    heroTitle?: string | undefined;
    heroSubtitle?: string | undefined;
    heroVideoUrl?: string | undefined;
    heroButton1?: string | undefined;
    heroButton2?: string | undefined;
    newsletterText?: string | undefined;
    footerText?: string | undefined;
}, {
    heroTitle?: string | undefined;
    heroSubtitle?: string | undefined;
    heroVideoUrl?: string | undefined;
    heroButton1?: string | undefined;
    heroButton2?: string | undefined;
    newsletterText?: string | undefined;
    footerText?: string | undefined;
}>;
export declare const UpdateSettingsResponse: zod.ZodObject<{
    heroTitle: zod.ZodString;
    heroSubtitle: zod.ZodString;
    heroVideoUrl: zod.ZodString;
    heroButton1: zod.ZodOptional<zod.ZodString>;
    heroButton2: zod.ZodOptional<zod.ZodString>;
    newsletterText: zod.ZodString;
    footerText: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    heroTitle: string;
    heroSubtitle: string;
    heroVideoUrl: string;
    newsletterText: string;
    footerText: string;
    heroButton1?: string | undefined;
    heroButton2?: string | undefined;
}, {
    heroTitle: string;
    heroSubtitle: string;
    heroVideoUrl: string;
    newsletterText: string;
    footerText: string;
    heroButton1?: string | undefined;
    heroButton2?: string | undefined;
}>;
//# sourceMappingURL=api.d.ts.map