/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Beach brand e-commerce API
 * OpenAPI spec version: 0.1.0
 */

export interface ProductUpdate {
  name?: string;
  description?: string;
  price?: number;
  images?: string[];
  sizes?: string[];
  colors?: string[];
  category?: string;
  stock?: number;
  isFeatured?: boolean;
  isBestSeller?: boolean;
}
