/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Beach brand e-commerce API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List products with optional filters
 */
export const ListProductsQueryParams = zod.object({
  "category": zod.coerce.string().optional(),
  "size": zod.coerce.string().optional(),
  "color": zod.coerce.string().optional(),
  "minPrice": zod.coerce.number().optional(),
  "maxPrice": zod.coerce.number().optional(),
  "search": zod.coerce.string().optional(),
  "featured": zod.coerce.boolean().optional(),
  "bestSeller": zod.coerce.boolean().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListProductsResponse = zod.object({
  "products": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})),
  "total": zod.number(),
  "page": zod.number(),
  "totalPages": zod.number()
})


/**
 * @summary Create a new product (admin)
 */
export const CreateProductBody = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number(),
  "images": zod.array(zod.string()).optional(),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean().optional(),
  "isBestSeller": zod.boolean().optional()
})

export const CreateProductResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})


/**
 * @summary Get product by ID
 */
export const GetProductParams = zod.object({
  "id": zod.coerce.number()
})

export const GetProductResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})


/**
 * @summary Update a product (admin)
 */
export const UpdateProductParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateProductBody = zod.object({
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "price": zod.number().optional(),
  "images": zod.array(zod.string()).optional(),
  "sizes": zod.array(zod.string()).optional(),
  "colors": zod.array(zod.string()).optional(),
  "category": zod.string().optional(),
  "stock": zod.number().optional(),
  "isFeatured": zod.boolean().optional(),
  "isBestSeller": zod.boolean().optional()
})

export const UpdateProductResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})


/**
 * @summary Delete a product (admin)
 */
export const DeleteProductParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteProductResponse = zod.void()


/**
 * @summary Get featured products for homepage
 */
export const GetFeaturedProductsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
export const GetFeaturedProductsResponse = zod.array(GetFeaturedProductsResponseItem)


/**
 * @summary Get best-selling products
 */
export const GetBestSellersResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
export const GetBestSellersResponse = zod.array(GetBestSellersResponseItem)


/**
 * @summary Get related products
 */
export const GetRelatedProductsParams = zod.object({
  "id": zod.coerce.number()
})

export const GetRelatedProductsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
export const GetRelatedProductsResponse = zod.array(GetRelatedProductsResponseItem)


/**
 * @summary Get cart by session
 */
export const GetCartQueryParams = zod.object({
  "sessionId": zod.coerce.string()
})

export const GetCartResponse = zod.object({
  "sessionId": zod.string(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "quantity": zod.number(),
  "size": zod.string(),
  "color": zod.string(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
})),
  "subtotal": zod.number(),
  "total": zod.number()
})


/**
 * @summary Add item to cart
 */
export const AddToCartBody = zod.object({
  "sessionId": zod.string(),
  "productId": zod.number(),
  "quantity": zod.number(),
  "size": zod.string(),
  "color": zod.string()
})

export const AddToCartResponse = zod.object({
  "sessionId": zod.string(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "quantity": zod.number(),
  "size": zod.string(),
  "color": zod.string(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
})),
  "subtotal": zod.number(),
  "total": zod.number()
})


/**
 * @summary Update cart item quantity
 */
export const UpdateCartItemParams = zod.object({
  "sessionId": zod.coerce.string(),
  "productId": zod.coerce.number()
})

export const UpdateCartItemBody = zod.object({
  "quantity": zod.number(),
  "size": zod.string().optional(),
  "color": zod.string().optional()
})

export const UpdateCartItemResponse = zod.object({
  "sessionId": zod.string(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "quantity": zod.number(),
  "size": zod.string(),
  "color": zod.string(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
})),
  "subtotal": zod.number(),
  "total": zod.number()
})


/**
 * @summary Remove item from cart
 */
export const RemoveFromCartParams = zod.object({
  "sessionId": zod.coerce.string(),
  "productId": zod.coerce.number()
})

export const RemoveFromCartResponse = zod.object({
  "sessionId": zod.string(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "quantity": zod.number(),
  "size": zod.string(),
  "color": zod.string(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
})),
  "subtotal": zod.number(),
  "total": zod.number()
})


/**
 * @summary Place an order
 */
export const CreateOrderBody = zod.object({
  "customerName": zod.string(),
  "customerEmail": zod.string(),
  "customerPhone": zod.string(),
  "address": zod.string(),
  "city": zod.string(),
  "paymentMethod": zod.string(),
  "sessionId": zod.string()
})

export const CreateOrderResponse = zod.object({
  "id": zod.number(),
  "customerName": zod.string(),
  "customerEmail": zod.string(),
  "customerPhone": zod.string(),
  "address": zod.string(),
  "city": zod.string(),
  "paymentMethod": zod.string(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "quantity": zod.number(),
  "size": zod.string(),
  "color": zod.string(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
})),
  "subtotal": zod.number(),
  "total": zod.number(),
  "status": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary List all orders (admin)
 */
export const ListOrdersResponseItem = zod.object({
  "id": zod.number(),
  "customerName": zod.string(),
  "customerEmail": zod.string(),
  "customerPhone": zod.string(),
  "address": zod.string(),
  "city": zod.string(),
  "paymentMethod": zod.string(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "quantity": zod.number(),
  "size": zod.string(),
  "color": zod.string(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
})),
  "subtotal": zod.number(),
  "total": zod.number(),
  "status": zod.string(),
  "createdAt": zod.string()
})
export const ListOrdersResponse = zod.array(ListOrdersResponseItem)


/**
 * @summary Get wishlist by session
 */
export const GetWishlistQueryParams = zod.object({
  "sessionId": zod.coerce.string()
})

export const GetWishlistResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
export const GetWishlistResponse = zod.array(GetWishlistResponseItem)


/**
 * @summary Toggle product in wishlist
 */
export const AddToWishlistBody = zod.object({
  "sessionId": zod.string(),
  "productId": zod.number()
})

export const AddToWishlistResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
export const AddToWishlistResponse = zod.array(AddToWishlistResponseItem)


/**
 * @summary List customer reviews
 */
export const ListReviewsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "rating": zod.number(),
  "comment": zod.string(),
  "location": zod.string(),
  "avatar": zod.string().nullish()
})
export const ListReviewsResponse = zod.array(ListReviewsResponseItem)


/**
 * @summary Admin login with password
 */
export const AdminLoginBody = zod.object({
  "password": zod.string()
})

export const AdminLoginResponse = zod.object({
  "success": zod.boolean(),
  "token": zod.string()
})


/**
 * @summary Get admin dashboard statistics
 */
export const GetAdminStatsResponse = zod.object({
  "totalOrders": zod.number(),
  "totalRevenue": zod.number(),
  "totalProducts": zod.number(),
  "totalCustomers": zod.number(),
  "recentOrders": zod.array(zod.object({
  "id": zod.number(),
  "customerName": zod.string(),
  "customerEmail": zod.string(),
  "customerPhone": zod.string(),
  "address": zod.string(),
  "city": zod.string(),
  "paymentMethod": zod.string(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "quantity": zod.number(),
  "size": zod.string(),
  "color": zod.string(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "price": zod.number(),
  "images": zod.array(zod.string()),
  "sizes": zod.array(zod.string()),
  "colors": zod.array(zod.string()),
  "category": zod.string(),
  "stock": zod.number(),
  "isFeatured": zod.boolean(),
  "isBestSeller": zod.boolean()
})
})),
  "subtotal": zod.number(),
  "total": zod.number(),
  "status": zod.string(),
  "createdAt": zod.string()
}))
})


/**
 * @summary Get site settings (hero, footer, newsletter)
 */
export const GetSettingsResponse = zod.object({
  "heroTitle": zod.string(),
  "heroSubtitle": zod.string(),
  "heroVideoUrl": zod.string(),
  "heroButton1": zod.string().optional(),
  "heroButton2": zod.string().optional(),
  "newsletterText": zod.string(),
  "footerText": zod.string()
})


/**
 * @summary Update site settings (admin)
 */
export const UpdateSettingsBody = zod.object({
  "heroTitle": zod.string().optional(),
  "heroSubtitle": zod.string().optional(),
  "heroVideoUrl": zod.string().optional(),
  "heroButton1": zod.string().optional(),
  "heroButton2": zod.string().optional(),
  "newsletterText": zod.string().optional(),
  "footerText": zod.string().optional()
})

export const UpdateSettingsResponse = zod.object({
  "heroTitle": zod.string(),
  "heroSubtitle": zod.string(),
  "heroVideoUrl": zod.string(),
  "heroButton1": zod.string().optional(),
  "heroButton2": zod.string().optional(),
  "newsletterText": zod.string(),
  "footerText": zod.string()
})


