/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Beach brand e-commerce API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Product {
  id: number;
  name: string;
  /** @nullable */
  description?: string | null;
  price: number;
  images: string[];
  sizes: string[];
  colors: string[];
  category: string;
  stock: number;
  isFeatured: boolean;
  isBestSeller: boolean;
}

export interface ProductInput {
  name: string;
  description?: string;
  price: number;
  images?: string[];
  sizes: string[];
  colors: string[];
  category: string;
  stock: number;
  isFeatured?: boolean;
  isBestSeller?: boolean;
}

export interface ProductUpdate {
  name?: string;
  description?: string;
  price?: number;
  images?: string[];
  sizes?: string[];
  colors?: string[];
  category?: string;
  stock?: number;
  isFeatured?: boolean;
  isBestSeller?: boolean;
}

export interface ProductListResponse {
  products: Product[];
  total: number;
  page: number;
  totalPages: number;
}

export interface CartItem {
  id: number;
  productId: number;
  quantity: number;
  size: string;
  color: string;
  product: Product;
}

export interface Cart {
  sessionId: string;
  items: CartItem[];
  subtotal: number;
  total: number;
}

export interface CartItemInput {
  sessionId: string;
  productId: number;
  quantity: number;
  size: string;
  color: string;
}

export interface CartItemUpdate {
  quantity: number;
  size?: string;
  color?: string;
}

export interface Order {
  id: number;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  address: string;
  city: string;
  paymentMethod: string;
  items: CartItem[];
  subtotal: number;
  total: number;
  status: string;
  createdAt: string;
}

export interface OrderInput {
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  address: string;
  city: string;
  paymentMethod: string;
  sessionId: string;
}

export interface Review {
  id: number;
  name: string;
  rating: number;
  comment: string;
  location: string;
  /** @nullable */
  avatar?: string | null;
}

export interface WishlistInput {
  sessionId: string;
  productId: number;
}

export interface AdminLoginInput {
  password: string;
}

export interface AdminAuth {
  success: boolean;
  token: string;
}

export interface AdminStats {
  totalOrders: number;
  totalRevenue: number;
  totalProducts: number;
  totalCustomers: number;
  recentOrders: Order[];
}

export interface SiteSettings {
  heroTitle: string;
  heroSubtitle: string;
  heroVideoUrl: string;
  heroButton1?: string;
  heroButton2?: string;
  newsletterText: string;
  footerText: string;
}

export interface SiteSettingsUpdate {
  heroTitle?: string;
  heroSubtitle?: string;
  heroVideoUrl?: string;
  heroButton1?: string;
  heroButton2?: string;
  newsletterText?: string;
  footerText?: string;
}

export type ListProductsParams = {
category?: string;
size?: string;
color?: string;
minPrice?: number;
maxPrice?: number;
search?: string;
featured?: boolean;
bestSeller?: boolean;
page?: number;
limit?: number;
};

export type GetCartParams = {
sessionId: string;
};

export type GetWishlistParams = {
sessionId: string;
};

