/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Beach brand e-commerce API
 * OpenAPI spec version: 0.1.0
 */

export interface CartItemUpdate {
  quantity: number;
  size?: string;
  color?: string;
}
